#pragma once

#include "function.h"

// LAYERS DEFINITIONS
#define WINDOWS 0
#define LINUX 1
#define MACOS 2

#define PRIMARY 3
#define PRIMARY_WINDOWS 4
#define PRIMARY_MACOS 5

COND_LAYER(LINUX, PRIMARY, PRIMARY_LINUX)
COND_LAYER(MACOS, PRIMARY, PRIMARY_MACOS)

#define SECONDARY 6
#define SECONDARY_LINUX 7
#define SECONDARY_MACOS 8

COND_LAYER(LINUX, SECONDARY, SECONDARY_LINUX)
COND_LAYER(MACOS, SECONDARY, SECONDARY_MACOS)

#define TERTIARY 9
#define TERTIARY_LINUX 10
#define TERTIARY_MACOS 11

COND_LAYER(PRIMARY, SECONDARY, TERTIARY)
COND_LAYER(LINUX, TERTIARY, TERTIARY_LINUX)
COND_LAYER(MACOS, TERTIARY, TERTIARY_MACOS)

#define NUMPAD 12

#define GAMING 13
#define GAMING_2 14