#pragma once

#include "function.h"

// LAYERS DEFINITIONS
#define WINDOWS 0
#define MACOS 1 // to layer or toggle layer ?

#define PRIMARY 2
#define PRIMARY_MACOS 3

COND_LAYER(MACOS, PRIMARY, PRIMARY_MACOS)

#define SECONDARY 4
#define SECONDARY_MACOS 5

COND_LAYER(MACOS, SECONDARY, SECONDARY_MACOS)

#define TERTIARY 6
#define TERTIARY_MACOS 7

COND_LAYER(PRIMARY, SECONDARY, TERTIARY)
COND_LAYER(MACOS, TERTIARY, TERTIARY_MACOS)

#define NUMPAD 8

#define GAMING 9
#define GAMING_2 10