# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Macros
CONFIG_ZMK_MACRO_DEFAULT_WAIT_MS=0
CONFIG_ZMK_MACRO_DEFAULT_TAP_MS=0